pub mod model;
pub mod rag;
pub mod inference;
pub mod tools;

use crate::model::get_model;
use crate::inference::stream_stem_tutor_inference;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    eprintln!("Info: Initializing Tauri application, pre-loading model...");
    if let Err(e) = get_model() {
        eprintln!("Warning: failed to pre-load model at startup: {e}");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![stream_stem_tutor_inference])
        .run(tauri::generate_context!())
        .expect("Tauri runtime initialization failure");
}

#[cfg(test)]
mod tests {
    use super::*;
    use llama_cpp_2::model::AddBos;
    use llama_cpp_2::llama_batch::LlamaBatch;
    use llama_cpp_2::sampling::LlamaSampler;
    use crate::model::{get_model, get_backend, build_context_params, N_BATCH, N_CTX};

    #[test]
    #[ignore]
    fn test_model_tokens() {
        let model = get_model().unwrap();

        let bos = model.token_bos();
        let eos = model.token_eos();
        println!("BOS token: {:?}", bos);
        println!("EOS token: {:?}", eos);

        if let Ok(bytes) = model.token_to_piece_bytes(bos, 128, true, None) {
            println!("BOS token detokenized: {:?}", String::from_utf8_lossy(&bytes));
        }
        if let Ok(bytes) = model.token_to_piece_bytes(eos, 128, true, None) {
            println!("EOS token detokenized: {:?}", String::from_utf8_lossy(&bytes));
        }

        // Check token IDs 0 to 20
        for id in 0..20 {
            let token = llama_cpp_2::token::LlamaToken(id);
            if let Ok(bytes) = model.token_to_piece_bytes(token, 128, true, None) {
                println!("Token {}: {:?}", id, String::from_utf8_lossy(&bytes));
            }
        }
    }

    #[test]
    #[ignore]
    fn test_generation() {
        let model = get_model().unwrap();
        let backend = get_backend();

        let ctx_params = build_context_params();
        let mut ctx = model.new_context(backend, ctx_params).unwrap();

        let system_prompt = "You are a Localized STEM Virtual Lab Tutor. Explain concepts step-by-step. Detail all mathematical derivations, physical laws, and chemical reactions clearly. If asked to translate, support multilingual outputs (e.g., Swahili, French) flawlessly.";
        let student_prompt = "Explain the magnetic field lines generated by a solenoid step-by-step. Detail the effect of number of turns, current strength, and relative permeability of a soft iron core.";
        let formatted_prompt = format!(
            "<|im_start|>system\n{}<|im_end|>\n<|im_start|>user\n{}<|im_end|>\n<|im_start|>assistant\n",
            system_prompt,
            student_prompt
        );

        let tokens = model.str_to_token(&formatted_prompt, AddBos::Always).unwrap();

        let mut batch = LlamaBatch::new(N_BATCH as usize, 1);
        let mut i = 0;
        while i < tokens.len() {
            let chunk_size = std::cmp::min(tokens.len() - i, N_BATCH as usize);
            batch.clear();
            for j in 0..chunk_size {
                let token_idx = i + j;
                let logits = token_idx == tokens.len() - 1;
                batch.add(tokens[token_idx], token_idx as i32, &[0], logits).unwrap();
            }
            ctx.decode(&mut batch).unwrap();
            i += chunk_size;
        }

        let mut sampler = LlamaSampler::chain_simple([
            LlamaSampler::greedy(),
        ]);

        let mut n_cur = tokens.len() as i32;
        let mut utf8_buffer: Vec<u8> = Vec::new();
        let mut output_str = String::new();

        while n_cur < N_CTX as i32 {
            let batch_idx = (batch.n_tokens() - 1) as i32;
            let token = sampler.sample(&ctx, batch_idx);

            if token == model.token_eos() {
                break;
            }

            let bytes = model.token_to_piece_bytes(token, 128, true, None).unwrap();
            utf8_buffer.extend_from_slice(&bytes);

            match std::str::from_utf8(&utf8_buffer) {
                Ok(valid_str) => {
                    output_str.push_str(valid_str);
                    utf8_buffer.clear();
                }
                Err(utf8_err) => {
                    let valid_up_to = utf8_err.valid_up_to();
                    if let Some(error_len) = utf8_err.error_len() {
                        let valid_part = &utf8_buffer[..valid_up_to];
                        output_str.push_str(&String::from_utf8_lossy(valid_part));
                        utf8_buffer = utf8_buffer[valid_up_to + error_len..].to_vec();
                    } else {
                        if valid_up_to > 0 {
                            let valid_part = &utf8_buffer[..valid_up_to];
                            output_str.push_str(std::str::from_utf8(valid_part).unwrap());
                            utf8_buffer = utf8_buffer[valid_up_to..].to_vec();
                        }
                    }
                }
            }

            sampler.accept(token);

            batch.clear();
            batch.add(token, n_cur, &[0], true).unwrap();

            ctx.decode(&mut batch).unwrap();

            n_cur += 1;
        }

        if !utf8_buffer.is_empty() {
            output_str.push_str(&String::from_utf8_lossy(&utf8_buffer));
        }

        println!("--- Generated Output ---\n{}", output_str);
        assert!(!output_str.is_empty());
        assert!(output_str.contains("solenoid") || output_str.contains("Solenoid"));
    }
}