<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';
  import { listen } from '@tauri-apps/api/event';
  import { onMount } from 'svelte';

  let studentInput = '';
  let terminalBuffer = 'Select a lab module from the shortcuts or input a custom science experiment to begin...';
  let isGenerating = false;
  let isFirstToken = false;
  let activeModule = '';

  interface ChatMessage {
    role: "user" | "assistant";
    content: string;
  }
  let chatHistory: ChatMessage[] = [];

  function compileChatMLPrompt(newQuery: string): string {
    const systemPrompt = "You are a Localized STEM Virtual Lab Tutor. Explain concepts step-by-step. Detail all mathematical derivations, physical laws, and chemical reactions clearly. If asked to translate, support multilingual outputs (e.g., Swahili, French) flawlessly.";
    const lastTurnsMessages = chatHistory.slice(-6);
    let prompt = `<|im_start|>system\n${systemPrompt}<|im_end|>\n`;
    for (const msg of lastTurnsMessages) {
      prompt += `<|im_start|>${msg.role}\n${msg.content}<|im_end|>\n`;
    }
    prompt += `<|im_start|>user\n${newQuery}<|im_end|>\n<|im_start|>assistant\n`;
    return prompt;
  }

  function clearHistory() {
    chatHistory = [];
    terminalBuffer = 'Select a lab module from the shortcuts or input a custom science experiment to begin...';
  }

  $: formattedConsole = formatConsoleForAppSvelte(chatHistory, terminalBuffer);
  
  function formatConsoleForAppSvelte(history: ChatMessage[], buffer: string): string {
    let html = "";
    for (const msg of history) {
      if (msg.role === "user") {
        const escapedContent = msg.content
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        html += `<div class="terminal-user-query"><span class="cmd-prompt">&gt; Student:</span> <span class="query-text">${escapedContent}</span></div>`;
      } else if (msg.role === "assistant") {
        html += `<div class="terminal-assistant-response">${msg.content}</div>`;
      }
    }
    if (buffer) {
      html += `<div class="terminal-current-stream">${buffer}</div>`;
    }
    return html;
  }

  // Curated interactive lab shortcuts for offline users
  const labShortcuts = [
    { 
      name: "🧲 Electromagnetism", 
      prompt: "Explain the magnetic field lines generated by a solenoid step-by-step.",
      desc: "Solenoid flux lines, right-hand rule, and core permeability."
    },
    { 
      name: "📐 Pendulum Period", 
      prompt: "Write the mathematical derivation for a simple pendulum's period under gravity.",
      desc: "Small-angle approximation, torque equations, and string length."
    },
    { 
      name: "🧪 Ideal Gas Law", 
      prompt: "Explain how changing temperature affects volume using molecular kinetic theory.",
      desc: "Gas constants, elastic collisions, and thermal expansion dynamics."
    }
  ];

  onMount(async () => {
    // Intercept native incoming tokens streamed directly from the Rust backend thread loop
    await listen<{ token: string }>('adtc-token-stream', (event) => {
      if (isFirstToken) {
        terminalBuffer = ""; // Flush initialization strings instantly upon first token arrival
        isFirstToken = false;
      }
      terminalBuffer += event.payload.token;

      // Smooth scroll to the bottom of the simulator output terminal
      const consoleView = document.getElementById('terminal-view');
      if (consoleView) {
        consoleView.scrollTop = consoleView.scrollHeight;
      }
    });
  });

  async function launchSimulation(queryText: string, label: string = "Custom Query") {
    if (!queryText.trim() || isGenerating) return;
    
    const compiledPrompt = compileChatMLPrompt(queryText);
    studentInput = '';
    chatHistory.push({ role: "user", content: queryText });

    isGenerating = true;
    isFirstToken = true;
    activeModule = label;
    terminalBuffer = `[SYSTEM]: Connecting to offline GGML backend...\n` +
                     `[SYSTEM]: Pinned Core: 4 Threads (-t 4)\n` +
                     `[SYSTEM]: Context Cache: FP16 active (Strict 3,072 max tokens)\n` +
                     `[SYSTEM]: Loading local Qwen3.5 ~2B model parameters...\n` +
                     `[SYSTEM]: Pre-loading context arrays for: "${queryText}"...\n\n` +
                     `[SYSTEM]: Running inference... (Calculations started)\n\n`;
    
    try {
      await invoke('stream_stem_tutor_inference', { studentPrompt: compiledPrompt });
      chatHistory.push({ role: 'assistant', content: terminalBuffer });
      terminalBuffer += `\n\n[SYSTEM]: Inference complete. CPU resources released back to host OS.`;
    } catch (err) {
      terminalBuffer += `\n\n[CRITICAL ERROR]: ${err}`;
    } finally {
      isGenerating = false;
      isFirstToken = false;
    }
  }
</script>

<main class="app-viewport">
  <!-- Top Tech Banner -->
  <header class="app-header">
    <div class="header-main">
      <div class="brand">
        <span class="badge-dtc">ADTC 2026</span>
        <h1>🔬 Localized STEM Virtual Lab Tutor</h1>
      </div>
      <div class="status-indicator">
        <span class="pulse-dot"></span>
        <span class="status-text">100% Offline Mode</span>
      </div>
    </div>
    <p class="subtitle">Interactive Physics, Chemistry, & Mathematics Assistant (Optimized for 4-vCPU/8GB RAM Budget Laptop)</p>
  </header>

  <!-- Hardware Profiling Stats Panel -->
  <section class="profiling-panel">
    <div class="stat-card">
      <div class="stat-icon">🎛️</div>
      <div class="stat-content">
        <span class="stat-label">Thread Pinning</span>
        <span class="stat-value">4 vCPUs Pinned</span>
      </div>
    </div>
    <div class="stat-card">
      <div class="stat-icon">🧠</div>
      <div class="stat-content">
        <span class="stat-label">Active Context Size</span>
        <span class="stat-value">3,072 Tokens Cap</span>
      </div>
    </div>
    <div class="stat-card">
      <div class="stat-icon">💾</div>
      <div class="stat-content">
        <span class="stat-label">KV Cache Format</span>
        <span class="stat-value">FP16 Precision</span>
      </div>
    </div>
    <div class="stat-card">
      <div class="stat-icon">🔋</div>
      <div class="stat-content">
        <span class="stat-label">Model Target</span>
        <span class="stat-value">Qwen3.5 GGUF</span>
      </div>
    </div>
  </section>

  <!-- Interactive Lab Shortcuts -->
  <section class="shortcuts-panel">
    <h3>🧪 Quick Lab Modules:</h3>
    <div class="shortcut-grid">
      {#each labShortcuts as shortcut}
        <button 
          on:click={() => launchSimulation(shortcut.prompt, shortcut.name)} 
          disabled={isGenerating}
          class="shortcut-btn"
          class:active={activeModule === shortcut.name}
        >
          <span class="btn-name">{shortcut.name}</span>
          <span class="btn-desc">{shortcut.desc}</span>
        </button>
      {/each}
    </div>
  </section>

  <!-- Terminal Output Viewport -->
  <section class="console-section">
    <div class="console-header">
      <div class="console-title">
        <span class="console-icon">💻</span>
        <span>Simulator Terminal Output</span>
      </div>
      <div style="display: flex; align-items: center; gap: 0.75rem;">
        {#if chatHistory.length > 0}
          <button 
            on:click={clearHistory} 
            disabled={isGenerating} 
            class="btn-clear-console"
            title="Clear conversation history to free RAM/context"
          >
            🧹 Clear Context
          </button>
        {/if}
        {#if isGenerating}
          <span class="loader-pulse">⚡ Stream Active (Computing...)</span>
        {:else}
          <span class="status-ready">✓ System Idle</span>
        {/if}
      </div>
    </div>
    <div id="terminal-view" class="terminal-view">
      {@html formattedConsole}
    </div>
  </section>

  <!-- Interaction Tray -->
  <footer class="interaction-tray">
    <input 
      type="text" 
      bind:value={studentInput} 
      placeholder="Ask a custom science question (e.g., Explain the physics of centrifugal acceleration)..." 
      disabled={isGenerating}
      on:keydown={(e) => e.key === 'Enter' && launchSimulation(studentInput, "Custom Query")}
      class="student-input"
    />
    <button 
      on:click={() => launchSimulation(studentInput, "Custom Query")} 
      disabled={isGenerating || !studentInput.trim()}
      class="run-btn"
    >
      Run Experiment
    </button>
  </footer>
</main>

<style>
  :global(body) {
    margin: 0;
    font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    background-color: #0b0f19;
    color: #cbd5e1;
    overflow: hidden;
  }

  .app-viewport {
    display: flex;
    flex-direction: column;
    height: 100vh;
    padding: 1.5rem;
    box-sizing: border-box;
    gap: 1rem;
    background: radial-gradient(circle at top right, rgba(126, 34, 206, 0.15), transparent 60%);
  }

  /* Header Styles */
  .app-header {
    border-bottom: 1px solid #1e293b;
    padding-bottom: 0.75rem;
  }

  .header-main {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .brand {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .badge-dtc {
    background: linear-gradient(135deg, #a855f7 0%, #7e22ce 100%);
    color: #f8fafc;
    font-size: 0.75rem;
    padding: 0.25rem 0.6rem;
    border-radius: 4px;
    font-weight: 800;
    letter-spacing: 0.05em;
    box-shadow: 0 0 10px rgba(168, 85, 247, 0.4);
  }

  h1 {
    font-size: 1.35rem;
    font-weight: 700;
    margin: 0;
    color: #f8fafc;
    letter-spacing: -0.02em;
  }

  .status-indicator {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    background: rgba(22, 163, 74, 0.1);
    border: 1px solid rgba(22, 163, 74, 0.3);
    padding: 0.35rem 0.75rem;
    border-radius: 9999px;
  }

  .pulse-dot {
    width: 8px;
    height: 8px;
    background-color: #22c55e;
    border-radius: 50%;
    box-shadow: 0 0 8px #22c55e;
    animation: beacon 2s infinite;
  }

  .status-text {
    font-size: 0.75rem;
    font-weight: 600;
    color: #4ade80;
  }

  .subtitle {
    margin: 0.35rem 0 0 0;
    font-size: 0.8rem;
    color: #64748b;
  }

  /* Hardware Profiling Panel */
  .profiling-panel {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 0.75rem;
  }

  .stat-card {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    background: rgba(30, 41, 59, 0.4);
    border: 1px solid #1e293b;
    padding: 0.65rem;
    border-radius: 8px;
    backdrop-filter: blur(10px);
  }

  .stat-icon {
    font-size: 1.25rem;
  }

  .stat-content {
    display: flex;
    flex-direction: column;
  }

  .stat-label {
    font-size: 0.65rem;
    color: #64748b;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .stat-value {
    font-size: 0.8rem;
    font-weight: 700;
    color: #e2e8f0;
  }

  /* Lab Shortcuts */
  .shortcuts-panel h3 {
    margin: 0 0 0.5rem 0;
    font-size: 0.85rem;
    color: #94a3b8;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .shortcut-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 0.75rem;
  }

  .shortcut-btn {
    background: rgba(30, 41, 59, 0.3);
    border: 1px solid #1e293b;
    padding: 0.75rem;
    border-radius: 8px;
    cursor: pointer;
    text-align: left;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    transition: all 0.2s ease;
  }

  .shortcut-btn:hover:not(:disabled) {
    border-color: #a855f7;
    background: rgba(168, 85, 247, 0.05);
    box-shadow: 0 0 12px rgba(168, 85, 247, 0.1);
  }

  .shortcut-btn.active {
    border-color: #a855f7;
    background: rgba(168, 85, 247, 0.1);
  }

  .btn-name {
    font-size: 0.85rem;
    font-weight: 600;
    color: #f1f5f9;
  }

  .btn-desc {
    font-size: 0.7rem;
    color: #64748b;
  }

  /* Console Section */
  .console-section {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }

  .console-header {
    background: #090d16;
    border: 1px solid #1e293b;
    border-bottom: none;
    border-radius: 8px 8px 0 0;
    padding: 0.5rem 1rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .console-title {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-family: monospace;
    font-size: 0.75rem;
    color: #94a3b8;
  }

  .status-ready {
    font-size: 0.75rem;
    color: #10b981;
    font-family: monospace;
  }

  .loader-pulse {
    font-size: 0.75rem;
    color: #a855f7;
    font-family: monospace;
    animation: blink 1.5s infinite;
  }

  .terminal-view {
    background: #030712;
    border: 1px solid #1e293b;
    border-left: 3px solid #a855f7;
    border-radius: 0 0 8px 8px;
    padding: 1rem;
    flex-grow: 1;
    overflow-y: auto;
    font-family: 'JetBrains Mono', 'Fira Code', monospace;
    font-size: 0.85rem;
    line-height: 1.6;
    color: #38bdf8;
    white-space: pre-wrap;
    box-shadow: inset 0 2px 8px rgba(0, 0, 0, 0.8);
  }

  :global(.terminal-user-query) {
    background: rgba(168, 85, 247, 0.08);
    border-left: 2px solid #a855f7;
    padding: 0.35rem 0.6rem;
    margin: 0.5rem 0 0.8rem 0;
    border-radius: 2px;
  }

  :global(.query-text) {
    color: #f1f5f9;
    font-weight: 500;
  }

  :global(.terminal-assistant-response) {
    margin-bottom: 1rem;
    border-bottom: 1px dashed rgba(30, 41, 59, 0.6);
    padding-bottom: 0.8rem;
  }

  :global(.terminal-assistant-response:last-child) {
    border-bottom: none;
    padding-bottom: 0;
  }

  .btn-clear-console {
    background: rgba(30, 41, 59, 0.5);
    border: 1px solid #334155;
    color: #94a3b8;
    padding: 0.15rem 0.5rem;
    border-radius: 4px;
    font-size: 0.65rem;
    cursor: pointer;
    font-family: inherit;
    transition: all 0.2s ease;
  }

  .btn-clear-console:hover:not(:disabled) {
    background: rgba(239, 68, 68, 0.15);
    border-color: #ef4444;
    color: #f87171;
  }

  /* Interaction Tray */
  .interaction-tray {
    display: flex;
    gap: 0.75rem;
  }

  .student-input {
    flex-grow: 1;
    background: #0f172a;
    border: 1px solid #1e293b;
    color: #f8fafc;
    padding: 0.85rem 1rem;
    border-radius: 8px;
    font-size: 0.85rem;
    transition: all 0.2s ease;
  }

  .student-input:focus {
    outline: none;
    border-color: #a855f7;
    box-shadow: 0 0 10px rgba(168, 85, 247, 0.2);
  }

  .run-btn {
    background: linear-gradient(135deg, #a855f7 0%, #7e22ce 100%);
    color: #f8fafc;
    border: none;
    padding: 0 1.5rem;
    border-radius: 8px;
    font-weight: 600;
    font-size: 0.85rem;
    cursor: pointer;
    transition: all 0.2s ease;
    box-shadow: 0 4px 12px rgba(168, 85, 247, 0.2);
  }

  .run-btn:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 6px 16px rgba(168, 85, 247, 0.4);
  }

  .run-btn:disabled {
    background: #1e293b;
    color: #64748b;
    cursor: not-allowed;
    box-shadow: none;
    transform: none;
  }

  /* Animations */
  @keyframes beacon {
    0%, 100% { transform: scale(1); opacity: 1; }
    50% { transform: scale(1.2); opacity: 0.6; }
  }

  @keyframes blink {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }
</style>