<script lang="ts">
  import { invoke } from "@tauri-apps/api/core";
  import { listen } from "@tauri-apps/api/event";
  import { onMount, onDestroy } from "svelte";
  import katex from "katex";
  import "katex/dist/katex.min.css";


  let studentInput = $state("");
  let terminalBuffer = $state("Select a lab module from the shortcuts or input a custom science experiment to begin...");

  interface ChatMessage {
    role: "user" | "assistant";
    content: string;
  }
  let chatHistory: ChatMessage[] = $state([]);
  let isGenerating = $state(false);
  let isFirstToken = $state(false);
  let activeModule = $state("🧲 Electromagnetism");
  let activeSandboxTab = $state("solenoid"); // 'solenoid', 'pendulum', 'gas'

  // Performance metrics
  let tokenCount = $state(0);
  let timeTaken = $state(0);
  let tokenSpeed = $state("0.0");
  let startTime = 0;
  
  // Custom configuration state
  let numThreads = $state(4);
  let contextCap = $state(3072);
  let temperature = $state(0.1);
  let selectedModel = $state("qwen2.5-1.5b-instruct");

  // Simulation State: 1. Solenoid (Electromagnetism)
  let solenoidCurrent = $state(2.5); // Amperes (-5A to 5A)
  let solenoidTurns = $state(50); // N (10 to 100)
  let solenoidCore = $state(1000); // Relative Permeability (1 to 1000)
  const solenoidLength = 0.2; // meters (fixed 20cm)

  // Simulation State: 2. Pendulum
  let pendulumLength = $state(1.5); // meters (0.5m to 3m)
  let pendulumGravity = $state(9.81); // m/s^2 (Moon: 1.62, Earth: 9.81, Jupiter: 24.79)
  let pendulumAngle = $state(30); // degrees (initial release angle)
  let pendulumActive = $state(true);

  // Pendulum Physics Variables
  let theta = $state(30 * Math.PI / 180); // current angle in radians
  let omega = $state(0); // current angular velocity
  let pendulumTime = $state(0);
  let lastTime = 0;

  // Simulation State: 3. Gas Law
  let gasTemperature = $state(300); // Kelvin (100K to 600K)
  let gasVolume = $state(60); // % of max volume (20% to 100%)
  let gasParticlesCount = $state(40); // Number of gas molecules (10 to 80)
  let gasPressureMeasured = $state(0); // measured from wall collisions
  let canvasEl: HTMLCanvasElement | null = $state(null);

  // Gas particle physics
  interface Particle {
    x: number;
    y: number;
    vx: number;
    vy: number;
    radius: number;
    color: string;
  }
  let particles: Particle[] = [];
  let momentumTransferred = 0;
  let collisionTimeElapsed = 0;

  // Pre-defined Lab Shortcuts
  const labShortcuts = [
    { 
      name: "🧲 Electromagnetism", 
      prompt: "Explain the magnetic field lines generated by a solenoid step-by-step. Detail the effect of number of turns, current strength, and relative permeability of a soft iron core.",
      desc: "Solenoid flux, permeability, and B-field derivation.",
      tab: "solenoid"
    },
    { 
      name: "📐 Pendulum Period", 
      prompt: "Derive the mathematical formula for a simple pendulum's swing period under gravity. Compare the small-angle approximation with actual behavior at larger angles.",
      desc: "Torque, restoring force, and elliptic period corrections.",
      tab: "pendulum"
    },
    { 
      name: "🧪 Ideal Gas Law", 
      prompt: "Detail the molecular kinetic theory of gas. Explain how decreasing the volume increases collision rate and pressure, and how temperature scales velocity.",
      desc: "Root-mean-square velocity, pressure collisions, and PV=nRT.",
      tab: "gas"
    }
  ];

  // Solenoid B-Field Calculation
  // B = u0 * ur * (N/L) * I
  const U0 = 4 * Math.PI * 1e-7; // permeability of free space
  let bFieldStrength = $derived(
    U0 * solenoidCore * (solenoidTurns / solenoidLength) * solenoidCurrent
  );

  // Pendulum Theoretical period
  // T0 = 2*pi * sqrt(L/g)
  let pendulumPeriodT0 = $derived(
    2 * Math.PI * Math.sqrt(pendulumLength / pendulumGravity)
  );
  // Correction: T = T0 * (1 + 1/16 * theta0^2)
  let pendulumPeriodT = $derived(
    pendulumPeriodT0 * (1 + (1 / 16) * Math.pow(pendulumAngle * Math.PI / 180, 2))
  );

  // Energies: mass = 1kg
  let mass = 1.0;
  let kineticEnergy = $derived(0.5 * mass * Math.pow(pendulumLength * omega, 2));
  let h = $derived(pendulumLength * (1 - Math.cos(theta)));
  let potentialEnergy = $derived(mass * pendulumGravity * h);
  let totalEnergy = $derived(kineticEnergy + potentialEnergy);

  // Bob position calculations for SVG drawing
  const pendulumScale = 160 / 3.0; // scale length: 3m = 160px
  let currentLenPx = $derived(pendulumLength * pendulumScale);
  let bobX = $derived(200 + currentLenPx * Math.sin(theta));
  let bobY = $derived(15 + currentLenPx * Math.cos(theta));

  // Ideal Gas Law calculations
  // P_theory = nRT/V (with scaling factor for visual metrics)
  // R = 8.314
  let gasPressureTheory = $derived(
    (gasParticlesCount * 8.314 * gasTemperature) / (gasVolume * 10)
  );

  // Svelte 5 helper: Safe HTML Markdown formatting with LaTeX Math (KaTeX) and collapsible <think> blocks
  function formatMarkdown(text: string) {
    if (!text) return "";

    const mathBlocks: string[] = [];

    // 1. Extract Block Math ($$...$$)
    let processedText = text.replace(/\$\$([\s\S]*?)\$\$/g, (_, math) => {
      const placeholder = `__MATH_BLOCK_${mathBlocks.length}__`;
      mathBlocks.push(math.trim());
      return placeholder;
    });

    // 2. Extract Inline Math ($...$)
    processedText = processedText.replace(/\$([^\$\s](?:[^\$]*?[^\$\s])?)\$/g, (_, math) => {
      const placeholder = `__MATH_INLINE_${mathBlocks.length}__`;
      mathBlocks.push(math.trim());
      return placeholder;
    });

    // 3. Extract <think> block if present
    let thinkHtml = "";
    const thinkStart = processedText.indexOf("<think>");
    if (thinkStart !== -1) {
      const thinkEnd = processedText.indexOf("</think>", thinkStart);
      let thinkingContent = "";
      if (thinkEnd !== -1) {
        thinkingContent = processedText.substring(thinkStart + 7, thinkEnd);
        processedText = processedText.substring(0, thinkStart) + processedText.substring(thinkEnd + 8);
      } else {
        thinkingContent = processedText.substring(thinkStart + 7);
        processedText = processedText.substring(0, thinkStart);
      }

      // Format thinking content using markdown rules (without thinking block wrapping itself)
      thinkingContent = formatMarkdownCore(thinkingContent);

      // Collapsible details element for thinking process: open during generation, closed when done
      const isOpen = !text.includes("</think>");
      thinkHtml = `
        <details class="term-think-details" ${isOpen ? "open" : ""}>
          <summary class="term-think-summary">🧠 Tutor's Thought Process</summary>
          <div class="term-think-body">${thinkingContent}</div>
        </details>
      `;
    }

    // 4. Format core markdown on the main body
    processedText = formatMarkdownCore(processedText);

    // Helper to format headings, bold/italics, lists, and code blocks
    function formatMarkdownCore(rawText: string) {
      if (!rawText) return "";
      let html = rawText
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");
        
      // Headings
      html = html.replace(/^### (.*?)$/gm, '<h3 class="term-h3">$1</h3>');
      html = html.replace(/^## (.*?)$/gm, '<h2 class="term-h2">$1</h2>');
      html = html.replace(/^# (.*?)$/gm, '<h1 class="term-h1">$1</h1>');
      
      // Bold & Italics
      html = html.replace(/\*\*(.*?)\*\*/g, '<strong class="term-bold">$1</strong>');
      html = html.replace(/\*(.*?)\*/g, '<em class="term-italic">$1</em>');
      
      // Code blocks
      html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => {
        return `<pre class="term-code-block"><div class="code-lang">${lang || 'code'}</div><code>${code}</code></pre>`;
      });

      // Inline code
      html = html.replace(/`(.*?)`/g, '<code class="term-code">$1</code>');
      
      // Bullet list items
      html = html.replace(/^\s*[\*\-]\s+(.*?)$/gm, '<li class="term-li">$1</li>');

      // Special lines
      html = html.replace(/^\[SYSTEM\]:(.*?)$/gm, '<span class="system-msg">[SYSTEM]: $1</span>');
      html = html.replace(/^\[CRITICAL ERROR\]:(.*?)$/gm, '<span class="error-msg">[CRITICAL ERROR]: $1</span>');
      
      // Newlines
      html = html.replace(/\n/g, '<br/>');
      
      return html;
    }

    // 5. Restore and render KaTeX formulas
    for (let i = 0; i < mathBlocks.length; i++) {
      const blockPlaceholder = `__MATH_BLOCK_${i}__`;
      if (processedText.includes(blockPlaceholder) || thinkHtml.includes(blockPlaceholder)) {
        try {
          const rendered = katex.renderToString(mathBlocks[i], { displayMode: true, throwOnError: false });
          processedText = processedText.replace(blockPlaceholder, rendered);
          thinkHtml = thinkHtml.replace(blockPlaceholder, rendered);
        } catch (e) {
          const errorHtml = `<span class="math-error">${mathBlocks[i]}</span>`;
          processedText = processedText.replace(blockPlaceholder, errorHtml);
          thinkHtml = thinkHtml.replace(blockPlaceholder, errorHtml);
        }
      }
      
      const inlinePlaceholder = `__MATH_INLINE_${i}__`;
      if (processedText.includes(inlinePlaceholder) || thinkHtml.includes(inlinePlaceholder)) {
        try {
          const rendered = katex.renderToString(mathBlocks[i], { displayMode: false, throwOnError: false });
          processedText = processedText.replace(inlinePlaceholder, rendered);
          thinkHtml = thinkHtml.replace(inlinePlaceholder, rendered);
        } catch (e) {
          const errorHtml = `<span class="math-error">${mathBlocks[i]}</span>`;
          processedText = processedText.replace(inlinePlaceholder, errorHtml);
          thinkHtml = thinkHtml.replace(inlinePlaceholder, errorHtml);
        }
      }
    }

    // Return combined HTML
    return thinkHtml + processedText;
  }

  // Compile the sliding window prompt
  function compileChatMLPrompt(newQuery: string): string {
    const systemPrompt = "You are a Localized STEM Virtual Lab Tutor. Explain concepts step-by-step. Detail all mathematical derivations, physical laws, and chemical reactions clearly. If asked to translate, support multilingual outputs (e.g., Swahili, French) flawlessly.";
    
    // Keep only the last 3 turns of dialogue prior to the current newQuery.
    // 3 turns = 6 messages.
    const lastTurnsMessages = chatHistory.slice(-6);
    
    let prompt = `<|im_start|>system\n${systemPrompt}<|im_end|>\n`;
    for (const msg of lastTurnsMessages) {
      prompt += `<|im_start|>${msg.role}\n${msg.content}<|im_end|>\n`;
    }
    
    prompt += `<|im_start|>user\n${newQuery}<|im_end|>\n<|im_start|>assistant\n`;
    return prompt;
  }

  // Clear conversation history
  function clearHistory() {
    chatHistory = [];
    terminalBuffer = "Select a lab module from the shortcuts or input a custom science experiment to begin...";
  }

  let formattedConsole = $derived.by(() => {
    let html = "";
    for (const msg of chatHistory) {
      if (msg.role === "user") {
        const escapedContent = msg.content
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        html += `<div class="terminal-user-query"><span class="cmd-prompt">&gt; Student:</span> <span class="query-text">${escapedContent}</span></div>`;
      } else if (msg.role === "assistant") {
        html += `<div class="terminal-assistant-response">${formatMarkdown(msg.content)}</div>`;
      }
    }
    
    if (terminalBuffer) {
      html += `<div class="terminal-current-stream">${formatMarkdown(terminalBuffer)}</div>`;
    }
    
    return html;
  });

  // Auto scroll console on changes
  $effect(() => {
    if (formattedConsole || isGenerating) {
      const terminalEl = document.getElementById("terminal-view");
      if (terminalEl) {
        setTimeout(() => {
          terminalEl.scrollTop = terminalEl.scrollHeight;
        }, 10);
      }
    }
  });

  // Safely check if running inside Tauri shell
  const isTauri = typeof window !== "undefined" && (window as any).__TAURI_INTERNALS__ !== undefined;

  // Event listener management
  let unlistenTokenStream: (() => void) | null = null;

  onMount(async () => {
    if (isTauri) {
      // listen to token stream event from Rust tauri backend
      unlistenTokenStream = await listen<{ token: string }>("adtc-token-stream", (event) => {
        if (isFirstToken) {
          terminalBuffer = "";
          isFirstToken = false;
          startTime = performance.now();
          tokenCount = 0;
          timeTaken = 0;
        }
        
        terminalBuffer += event.payload.token;
        tokenCount++;
        timeTaken = (performance.now() - startTime) / 1000;
        
        if (timeTaken > 0) {
          tokenSpeed = (tokenCount / timeTaken).toFixed(1);
        }

        // Auto scroll console
        const terminalEl = document.getElementById("terminal-view");
        if (terminalEl) {
          terminalEl.scrollTop = terminalEl.scrollHeight;
        }
      });
    } else {
      console.info("[Mock Dev Mode] Bypassed native event listeners inside standard browser.");
    }
  });

  onDestroy(() => {
    if (unlistenTokenStream) unlistenTokenStream();
  });

  // Mock token streaming function for dev mode in standard web browsers
  async function mockTokenStreaming(prompt: string) {
    let mockText = "";
    const lowerPrompt = prompt.toLowerCase();
    
    if (lowerPrompt.includes("solenoid") || lowerPrompt.includes("magnet") || lowerPrompt.includes("electromagnetism")) {
      mockText = "### 1. Solenoid Magnetic Field Derivation\n\n" +
                 "A solenoid is a long coil of wire wrapped in a helical shape. When an electric current passes through it, a uniform magnetic field is generated inside its core.\n\n" +
                 "Using **Ampere's Law**:\n" +
                 "$$\\oint B \\cdot dl = \\mu_0 I_{\\text{enc}}$$\n\n" +
                 "For an ideal solenoid of length $L$ with $N$ turns, integrating along a rectangular loop yields:\n" +
                 "$$B \\cdot L = \\mu_0 \\mu_r N I$$\n\n" +
                 "Solving for $B$:\n" +
                 "$$B = \\mu_0 \\mu_r \\frac{N}{L} I$$\n\n" +
                 "### 2. Parameter Sensitivity Analysis\n" +
                 "- **Current ($I$)**: Reversing current direction flips magnetic poles (reversing the flux lines).\n" +
                 "- **Permeability ($\\mu_r$)**: Adding a soft iron core ($\\mu_r \\approx 1000$) concentrates magnetic field strength by 1000x compared to air!\n" +
                 "- **Turns Density ($N/L$)**: Increasing turns concentration raises magnetic flux lines density.";
    } else if (lowerPrompt.includes("pendulum") || lowerPrompt.includes("gravity") || lowerPrompt.includes("period")) {
      mockText = "### 1. Simple Pendulum Equation of Motion\n\n" +
                 "Applying **Newton's Second Law** to the angular motion of a mass $m$ suspended on a string of length $L$:\n" +
                 "$$\\tau = I \\alpha \\implies -m g L \\sin\\theta = m L^2 \\frac{d^2\\theta}{dt^2}$$\n\n" +
                 "This simplifies to the non-linear differential equation:\n" +
                 "$$\\frac{d^2\\theta}{dt^2} + \\frac{g}{L} \\sin\\theta = 0$$\n\n" +
                 "### 2. Period Approximations\n" +
                 "- **Small Angle Approximation**: For $\\sin\\theta \\approx \\theta$ (valid under $15^\\circ$):\n" +
                 "$$T_0 = 2 \\pi \\sqrt{\\frac{L}{g}}$$\n" +
                 "- **Elliptic Correction**: For larger angles, we use expansion series:\n" +
                 "$$T \\approx T_0 \\left(1 + \\frac{1}{16}\\theta_0^2\\right)$$\n\n" +
                 "This explains why amplitude changes the swing rate at high displacements!";
    } else if (lowerPrompt.includes("gas") || lowerPrompt.includes("ideal") || lowerPrompt.includes("temperature") || lowerPrompt.includes("kinetic")) {
      mockText = "### 1. Ideal Gas Law Derivation\n\n" +
                 "The state of an ideal gas is described by the equation:\n" +
                 "$$P V = n R T$$\n\n" +
                 "### 2. Kinetic Molecular Theory of Gases\n" +
                 "Molecules are modeled as elastic spheres in constant motion. The pressure $P$ exerted on the walls is due to momentum transfer during collisions:\n" +
                 "$$P = \\frac{1}{3} \\frac{N m v_{\\text{rms}}^2}{V}$$\n\n" +
                 "Where the root-mean-square velocity is:\n" +
                 "$$v_{\\text{rms}} = \\sqrt{\\frac{3 R T}{M}}$$\n\n" +
                 "- **Volume Reduction**: Halving volume doubles collision frequency (doubling pressure).\n" +
                 "- **Thermal Scaling**: Raising temperature makes molecules move faster, increasing collision speed and momentum.";
    } else {
      mockText = "### STEM Tutor Search Query Results\n\n" +
                 "You queried: **" + prompt + "**\n\n" +
                 "Analyzing offline scientific database indices...\n" +
                 "1. Identified primary physical principles related to context.\n" +
                 "2. Calculated dimensional parameters using local CPU cores.\n" +
                 "3. Ready to proceed with virtual simulation verification.";
    }

    const tokens = mockText.split(" ");
    if (isFirstToken) {
      terminalBuffer = "";
      isFirstToken = false;
      startTime = performance.now();
      tokenCount = 0;
      timeTaken = 0;
    }

    for (let i = 0; i < tokens.length; i++) {
      if (!isGenerating) break;
      
      const token = tokens[i] + " ";
      terminalBuffer += token;
      tokenCount++;
      timeTaken = (performance.now() - startTime) / 1000;
      if (timeTaken > 0) {
        tokenSpeed = (tokenCount / timeTaken).toFixed(1);
      }
      
      const terminalEl = document.getElementById("terminal-view");
      if (terminalEl) {
        terminalEl.scrollTop = terminalEl.scrollHeight;
      }
      
      await new Promise(resolve => setTimeout(resolve, 20 + Math.random() * 25));
    }
    
    // Set terminalBuffer to exact mockText and add to Svelte chat state
    terminalBuffer = mockText;
    chatHistory.push({ role: "assistant", content: mockText });
    
    terminalBuffer += `\n\n[SYSTEM]: Inference complete. CPU resources released back to operating system.`;
    isGenerating = false;
    isFirstToken = false;
  }

  // Launch local LLM simulation
  async function launchSimulation(queryText: string, label: string = "Custom Query", simulationTab?: string) {
    if (!queryText.trim() || isGenerating) return;
    
    // Compile sliding window ChatML prompt containing system prompt + last 3 turns of history + current query
    const compiledPrompt = compileChatMLPrompt(queryText);

    // Clear student input box
    studentInput = "";
    
    // Append the student's query to frontend state history
    chatHistory.push({ role: "user", content: queryText });

    isGenerating = true;
    isFirstToken = true;
    activeModule = label;
    tokenSpeed = "0.0";
    tokenCount = 0;
    timeTaken = 0;
    
    if (simulationTab) {
      activeSandboxTab = simulationTab;
    }

    terminalBuffer = `[SYSTEM]: Initializing connection to offline Llama.cpp C++ bindings...\n` +
                     `[SYSTEM]: Thread Allocation: ${numThreads} Cores (Strict Pinning)\n` +
                     `[SYSTEM]: Context Cache Bound: ${contextCap} Max Tokens\n` +
                     `[SYSTEM]: Core Memory Allocation: FP16 Key-Value Cache Format\n` +
                     `[SYSTEM]: Active Model Modelfile: /models/qwen2.5-1.5b-instruct-q4_k_m.gguf\n` +
                     `[SYSTEM]: Feeding query input prompt context...\n\n` +
                     `[SYSTEM]: Initiating matrix calculations on CPU threads. Generating explanation:\n\n`;

    if (isTauri) {
      try {
        await invoke("stream_stem_tutor_inference", { studentPrompt: compiledPrompt });
        
        // Push the compiled tutor response to frontend state history
        chatHistory.push({ role: "assistant", content: terminalBuffer });
        
        terminalBuffer += `\n\n[SYSTEM]: Inference complete. CPU resources released back to operating system.`;
      } catch (err) {
        terminalBuffer += `\n\n[CRITICAL ERROR]: ${err}`;
      } finally {
        isGenerating = false;
        isFirstToken = false;
      }
    } else {
      // Bypassed if running in web browser dev mode
      await mockTokenStreaming(queryText);
    }
  }

  // Animation Loop: Pendulum physics Solver
  function animatePendulum(timestamp: number) {
    if (!lastTime) lastTime = timestamp;
    let dt = (timestamp - lastTime) / 1000;
    if (dt > 0.1) dt = 0.1; // cap frame lag
    lastTime = timestamp;

    if (pendulumActive) {
      // Angular acceleration: alpha = -(g / L) * sin(theta)
      const alpha = -(pendulumGravity / pendulumLength) * Math.sin(theta);
      omega += alpha * dt;
      theta += omega * dt;
      pendulumTime += dt;
    }

    if (activeSandboxTab === "pendulum") {
      requestAnimationFrame(animatePendulum);
    }
  }

  // Svelte 5 Effect to toggle Pendulum physics solver
  $effect(() => {
    if (activeSandboxTab === "pendulum") {
      lastTime = 0;
      let frame = requestAnimationFrame(animatePendulum);
      return () => cancelAnimationFrame(frame);
    }
  });

  // Reset Pendulum Angle to initial state
  function resetPendulum() {
    theta = pendulumAngle * Math.PI / 180;
    omega = 0;
    pendulumTime = 0;
  }

  // Handle Pendulum initial angle slider changes
  $effect(() => {
    // When the user adjusts the slider, reset the swing to match the new initial angle
    if (pendulumAngle) {
      resetPendulum();
    }
  });

  // Gas particle initializer
  function initGasParticles(count: number, temp: number, vol: number) {
    if (!canvasEl) return;
    const width = (vol / 100) * 280 + 80; // min width 80px, max 360px
    const height = 210;
    particles = [];
    
    // Scale speed to T (v_rms is proportional to sqrt(T))
    const speedMultiplier = Math.sqrt(temp) * 0.18;

    for (let i = 0; i < count; i++) {
      const radius = 5;
      const x = radius + Math.random() * (width - 2 * radius);
      const y = radius + Math.random() * (height - 2 * radius);
      const angle = Math.random() * Math.PI * 2;
      const speed = (0.7 + Math.random() * 0.6) * speedMultiplier;
      
      particles.push({
        x,
        y,
        vx: Math.cos(angle) * speed,
        vy: Math.sin(angle) * speed,
        radius,
        // HSL temperature color styling (blue = cold, orange/red = hot)
        color: `hsl(${(1 - (temp - 100) / 500) * 200}, 85%, 60%)`
      });
    }
  }

  // Animation Loop: Gas Simulation Solver
  function animateGas(timestamp: number) {
    if (!canvasEl) return;
    const ctx = canvasEl.getContext("2d");
    if (!ctx) return;

    const width = (gasVolume / 100) * 280 + 80;
    const height = 210;

    // Clear canvas
    ctx.clearRect(0, 0, 400, 250);

    // Draw container boundaries
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 3;
    ctx.fillStyle = "rgba(15, 23, 42, 0.4)";
    ctx.strokeRect(0, 0, width, height);
    ctx.fillRect(0, 0, width, height);

    // Speed target based on current temperature
    const targetSpeedBase = Math.sqrt(gasTemperature) * 0.18;

    particles.forEach((p) => {
      // Slowly adjust speed of particle to match new temperature setting
      const speed = Math.sqrt(p.vx * p.vx + p.vy * p.vy);
      if (speed > 0 && Math.abs(speed - targetSpeedBase) > 0.05) {
        const ratio = targetSpeedBase / speed;
        p.vx *= ratio;
        p.vy *= ratio;
      }

      p.x += p.vx;
      p.y += p.vy;

      // Collide walls
      if (p.x - p.radius < 0) {
        p.x = p.radius;
        p.vx = -p.vx;
        momentumTransferred += 2 * Math.abs(p.vx);
      } else if (p.x + p.radius > width) {
        p.x = width - p.radius;
        p.vx = -p.vx;
        momentumTransferred += 2 * Math.abs(p.vx);
      }

      if (p.y - p.radius < 0) {
        p.y = p.radius;
        p.vy = -p.vy;
        momentumTransferred += 2 * Math.abs(p.vy);
      } else if (p.y + p.radius > height) {
        p.y = height - p.radius;
        p.vy = -p.vy;
        momentumTransferred += 2 * Math.abs(p.vy);
      }

      // Draw molecule
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
      ctx.fillStyle = p.color;
      // Add subtle glow matching particle temperature color
      ctx.shadowBlur = 4;
      ctx.shadowColor = p.color;
      ctx.fill();
      ctx.shadowBlur = 0;
    });

    // Particle-to-particle simple elastic collisions
    for (let i = 0; i < particles.length; i++) {
      for (let j = i + 1; j < particles.length; j++) {
        const p1 = particles[i];
        const p2 = particles[j];
        const dx = p2.x - p1.x;
        const dy = p2.y - p1.y;
        const dist = Math.sqrt(dx * dx + dy * dy);
        const minDist = p1.radius + p2.radius;

        if (dist < minDist) {
          const overlap = minDist - dist;
          const nx = dx / dist;
          const ny = dy / dist;

          // Resolve overlap
          p1.x -= nx * overlap * 0.5;
          p1.y -= ny * overlap * 0.5;
          p2.x += nx * overlap * 0.5;
          p2.y += ny * overlap * 0.5;

          // Swap normal velocities
          const kx = p1.vx - p2.vx;
          const ky = p1.vy - p2.vy;
          const normalVel = nx * kx + ny * ky;
          if (normalVel > 0) {
            p1.vx -= nx * normalVel;
            p1.vy -= ny * normalVel;
            p2.vx += nx * normalVel;
            p2.vy += ny * normalVel;
          }
        }
      }
    }

    // Accumulate pressure metric
    collisionTimeElapsed += 1 / 60;
    if (collisionTimeElapsed >= 0.5) {
      // P = (Sum(2 * m * v_normal)) / (time * perimeter)
      const perimeter = 2 * (width + height);
      gasPressureMeasured = (momentumTransferred / (collisionTimeElapsed * perimeter)) * 14;
      momentumTransferred = 0;
      collisionTimeElapsed = 0;
    }

    if (activeSandboxTab === "gas") {
      requestAnimationFrame(animateGas);
    }
  }

  // Svelte 5 Effect to trigger gas simulation
  $effect(() => {
    if (activeSandboxTab === "gas" && canvasEl) {
      initGasParticles(gasParticlesCount, gasTemperature, gasVolume);
      let frame = requestAnimationFrame(animateGas);
      return () => cancelAnimationFrame(frame);
    }
  });

  // Reinit particles when quantity or volume slider changes
  $effect(() => {
    if (activeSandboxTab === "gas" && canvasEl) {
      initGasParticles(gasParticlesCount, gasTemperature, gasVolume);
    }
  });
</script>

<main class="app-viewport">
  <!-- Dynamic Glowing Tech Header -->
  <header class="app-header">
    <div class="header-branding">
      <div class="logo-area">
        <span class="badge-challenge">ADTC 2026</span>
        <h1 class="gradient-text">Localized STEM Virtual Lab Tutor</h1>
      </div>
      <div class="system-pills">
        <div class="pill-green">
          <span class="pulse-beacon"></span>
          <span>100% Offline AI Server</span>
        </div>
        <div class="pill-info">
          <span>Latent CPU Matrix Engines</span>
        </div>
      </div>
    </div>
    <div class="header-desc-row">
      <p class="header-subtitle">Optimized Neural STEM Tutor & Physics Simulator for Low-spec 8GB RAM Budget Laptops</p>
      <div class="local-timestamp">
        <span class="time-label">Core Clock:</span>
        <span class="time-value">20:05 UTC</span>
      </div>
    </div>
  </header>

  <!-- Main Multi-Column Interface Grid -->
  <div class="dashboard-grid">
    
    <!-- LEFT PANEL: AI COGNITIVE TUTOR CONSOLE -->
    <div class="card panel-tutor">
      <!-- Hardware / Thread Configuration Panel -->
      <section class="config-ribbon">
        <div class="ribbon-header">
          <span>🔧 Backend Config:</span>
        </div>
        <div class="ribbon-fields">
          <label class="field-item">
            <span class="field-label">Threads:</span>
            <select bind:value={numThreads} disabled={isGenerating} class="select-small">
              <option value={2}>2 Threads</option>
              <option value={4}>4 Threads (Pin)</option>
              <option value={6}>6 Threads</option>
              <option value={8}>8 Threads</option>
            </select>
          </label>
          <label class="field-item">
            <span class="field-label">Cache Cap:</span>
            <select bind:value={contextCap} disabled={isGenerating} class="select-small">
              <option value={1024}>1024 Toks</option>
              <option value={2048}>2048 Toks</option>
              <option value={3072}>3072 Toks</option>
            </select>
          </label>
          <label class="field-item">
            <span class="field-label">Temp:</span>
            <input type="range" min="0.0" max="1.0" step="0.05" bind:value={temperature} disabled={isGenerating} class="slider-mini" />
            <span class="slider-val">{temperature}</span>
          </label>
        </div>
      </section>

      <!-- Quick STEM Module Shortcuts -->
      <section class="shortcuts-container">
        <div class="section-title-bar">
          <span class="title-icon">🧪</span>
          <h3>Quick Lab Modules:</h3>
        </div>
        <div class="shortcuts-grid">
          {#each labShortcuts as shortcut}
            <button 
              onclick={() => launchSimulation(shortcut.prompt, shortcut.name, shortcut.tab)} 
              disabled={isGenerating}
              class="shortcut-card"
              class:active={activeModule === shortcut.name}
            >
              <div class="shortcut-meta">
                <span class="shortcut-name">{shortcut.name}</span>
                <span class="shortcut-desc">{shortcut.desc}</span>
              </div>
              <div class="shortcut-arrow">→</div>
            </button>
          {/each}
        </div>
      </section>

      <!-- Terminal Output Screen -->
      <section class="console-wrapper">
        <div class="console-header-bar">
          <div class="console-title">
            <span class="cmd-prompt">>_</span>
            <span>Simulator Terminal Output</span>
          </div>
          <div class="console-metrics" style="display: flex; align-items: center;">
            {#if chatHistory.length > 0}
              <button 
                onclick={clearHistory} 
                disabled={isGenerating} 
                class="btn-clear-console"
                title="Clear conversation history to free RAM/context"
              >
                🧹 Clear Context
              </button>
            {/if}
            {#if isGenerating}
              <span class="indicator-computing">⚡ CPU Generating: {tokenSpeed} tok/s</span>
            {:else}
              <span class="indicator-idle">● Solver Idle</span>
            {/if}
          </div>
        </div>
        
        <div id="terminal-view" class="terminal-screen">
          <div class="terminal-feed">
            {@html formattedConsole}
            {#if isGenerating}
              <span class="blinking-cursor">▒</span>
            {/if}
          </div>
        </div>
      </section>

      <!-- Student Command Entry Tray -->
      <footer class="input-tray">
        <input 
          type="text" 
          bind:value={studentInput} 
          placeholder="Ask a custom science question (e.g., Explain the physics of centrifugal acceleration)..." 
          disabled={isGenerating}
          onkeydown={(e) => e.key === "Enter" && launchSimulation(studentInput, "Custom Query")}
          class="student-text-input"
        />
        <button 
          onclick={() => launchSimulation(studentInput, "Custom Query")} 
          disabled={isGenerating || !studentInput.trim()}
          class="btn-execute"
        >
          Run Experiment
        </button>
      </footer>
    </div>

    <!-- RIGHT PANEL: INTERACTIVE PHYSICAL SANDBOX -->
    <div class="card panel-sandbox">
      <!-- Sandbox Header Tabs -->
      <div class="sandbox-tabs">
        <button 
          class="tab-btn" 
          class:active={activeSandboxTab === "solenoid"} 
          onclick={() => { activeSandboxTab = "solenoid"; activeModule = "🧲 Electromagnetism"; }}
        >
          🧲 Solenoid Flux
        </button>
        <button 
          class="tab-btn" 
          class:active={activeSandboxTab === "pendulum"} 
          onclick={() => { activeSandboxTab = "pendulum"; activeModule = "📐 Pendulum Period"; }}
        >
          📐 Gravity Pendulum
        </button>
        <button 
          class="tab-btn" 
          class:active={activeSandboxTab === "gas"} 
          onclick={() => { activeSandboxTab = "gas"; activeModule = "🧪 Ideal Gas Law"; }}
        >
          🧪 Particle Gas Box
        </button>
      </div>

      <!-- ACTIVE SIMULATION WIDGET -->
      <div class="sandbox-viewport">
        {#if activeSandboxTab === "solenoid"}
          <!-- SOLENOID VISUALIZER -->
          <div class="sim-container">
            <h4 class="sim-title">Electromagnetic Solenoid Induction Sandbox</h4>
            
            <!-- SVG Solenoid Winding Drawing -->
            <div class="svg-wrapper">
              <svg viewBox="0 0 400 200" class="sim-svg">
                <!-- Core Layer (Back) -->
                {#if solenoidCore > 1}
                  <rect 
                    x="50" y="75" width="300" height="50" rx="4"
                    fill="url(#ironCoreGrad)" 
                    opacity={solenoidCore === 1000 ? 0.95 : 0.6}
                    stroke="#475569" stroke-width="1"
                  />
                {:else}
                  <!-- Air Core dashed borders -->
                  <rect 
                    x="50" y="75" width="300" height="50" rx="4"
                    fill="none" stroke="#475569" stroke-dasharray="4,4" stroke-width="1.5"
                  />
                {/if}

                <!-- Magnetic Field Lines (Drawn behind front coils) -->
                <!-- We draw 6 lines, speed and direction proportional to current, opacity to B-Field -->
                {#if Math.abs(solenoidCurrent) > 0.05}
                  <g opacity={Math.min(1.0, Math.abs(bFieldStrength) * 1200000 + 0.1)}>
                    <!-- Line 1: Center Axis Line -->
                    <line 
                      x1="10" y1="100" x2="390" y2="100" 
                      stroke="#06b6d4" stroke-width="1.5" stroke-dasharray="6,4"
                      style="animation: dash {10 / Math.abs(solenoidCurrent)}s linear infinite; animation-direction: {solenoidCurrent < 0 ? 'reverse' : 'normal'}"
                    />
                    <!-- Line 2 & 3: Inner field lines -->
                    <path 
                      d="M 40 90 Q 200 40 360 90" fill="none" 
                      stroke="#06b6d4" stroke-width="1.2" stroke-dasharray="5,5"
                      style="animation: dash {12 / Math.abs(solenoidCurrent)}s linear infinite; animation-direction: {solenoidCurrent < 0 ? 'reverse' : 'normal'}"
                    />
                    <path 
                      d="M 40 110 Q 200 160 360 110" fill="none" 
                      stroke="#06b6d4" stroke-width="1.2" stroke-dasharray="5,5"
                      style="animation: dash {12 / Math.abs(solenoidCurrent)}s linear infinite; animation-direction: {solenoidCurrent < 0 ? 'reverse' : 'normal'}"
                    />
                    <!-- Line 4 & 5: Outer wrapping lines -->
                    <path 
                      d="M 50 85 C 10 20, 390 20, 350 85" fill="none" 
                      stroke="#a855f7" stroke-width="1.0" stroke-dasharray="4,6"
                      style="animation: dash {15 / Math.abs(solenoidCurrent)}s linear infinite; animation-direction: {solenoidCurrent < 0 ? 'reverse' : 'normal'}"
                    />
                    <path 
                      d="M 50 115 C 10 180, 390 180, 350 115" fill="none" 
                      stroke="#a855f7" stroke-width="1.0" stroke-dasharray="4,6"
                      style="animation: dash {15 / Math.abs(solenoidCurrent)}s linear infinite; animation-direction: {solenoidCurrent < 0 ? 'reverse' : 'normal'}"
                    />
                  </g>
                {/if}

                <!-- Solenoid Coil Loops (Front 3D Overlay) -->
                <!-- We draw loops dynamically depending on Turns slider -->
                <g stroke="#f59e0b" stroke-width="3" stroke-linecap="round" fill="none">
                  {#each Array(Math.min(25, Math.ceil(solenoidTurns / 3))) as _, idx}
                    {@const xPos = 60 + idx * (280 / Math.min(25, Math.ceil(solenoidTurns / 3)))}
                    <!-- Half loop arc drawing front of core -->
                    <path d="M {xPos} 75 C {xPos + 5} 70, {xPos + 10} 130, {xPos + 15} 125" />
                  {/each}
                </g>

                <!-- Current flow vectors (indicators) -->
                {#if Math.abs(solenoidCurrent) > 0.1}
                  <text x="200" y="190" fill="#f59e0b" font-size="10" font-family="monospace" text-anchor="middle">
                    Current (I) Flow Direction: {solenoidCurrent > 0 ? 'LEFT ──> RIGHT' : 'RIGHT ──> LEFT'}
                  </text>
                {/if}

                <!-- Gradients Definition -->
                <defs>
                  <linearGradient id="ironCoreGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                    <stop offset="0%" stop-color="#475569" />
                    <stop offset="50%" stop-color="#94a3b8" />
                    <stop offset="100%" stop-color="#334155" />
                  </linearGradient>
                </defs>
              </svg>
            </div>

            <!-- Parameters Sliders panel -->
            <div class="sliders-grid">
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Current ($I$)</span>
                  <span class="value-highlight">{solenoidCurrent.toFixed(1)} A</span>
                </div>
                <input type="range" min="-5.0" max="5.0" step="0.1" bind:value={solenoidCurrent} class="slider-full" />
              </div>
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Turns ($N$)</span>
                  <span class="value-highlight">{solenoidTurns} turns</span>
                </div>
                <input type="range" min="10" max="100" step="5" bind:value={solenoidTurns} class="slider-full" />
              </div>
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Core Material ($\mu_r$)</span>
                  <span class="value-highlight">
                    {solenoidCore === 1 ? 'Air (1)' : solenoidCore === 100 ? 'Cobalt Alloy (100)' : 'Soft Iron (1000)'}
                  </span>
                </div>
                <div class="material-options">
                  <button class="choice-btn" class:selected={solenoidCore === 1} onclick={() => solenoidCore = 1}>Air</button>
                  <button class="choice-btn" class:selected={solenoidCore === 100} onclick={() => solenoidCore = 100}>Alloy</button>
                  <button class="choice-btn" class:selected={solenoidCore === 1000} onclick={() => solenoidCore = 1000}>Iron</button>
                </div>
              </div>
            </div>

            <!-- Solver Math Dashboard -->
            <div class="solver-output-box">
              <div class="formula-line">
                <span class="formula-label">Governing Equation:</span>
                <span class="formula-text">B = &mu;<sub>0</sub> &middot; &mu;<sub>r</sub> &middot; (N / L) &middot; I</span>
              </div>
              <div class="math-breakdown">
                <p>
                  B = (1.257&times;10<sup>-6</sup>) &times; {solenoidCore} &times; ({solenoidTurns} / 0.2m) &times; {solenoidCurrent.toFixed(2)} A
                </p>
                <div class="main-metric">
                  <span class="metric-label">Magnetic Flux Density (B):</span>
                  <span class="metric-val">
                    {#if Math.abs(bFieldStrength) < 1e-4}
                      {(bFieldStrength * 1e6).toFixed(2)} &mu;T
                    {:else}
                      {(bFieldStrength * 1000).toFixed(2)} mT
                    {/if}
                  </span>
                </div>
              </div>
            </div>
          </div>

        {:else if activeSandboxTab === "pendulum"}
          <!-- PENDULUM VISUALIZER -->
          <div class="sim-container">
            <h4 class="sim-title">Simple Pendulum Gravity Harmonic Sandbox</h4>
            
            <div class="svg-wrapper">
              <svg viewBox="0 0 400 240" class="sim-svg">
                <!-- Anchor Ceiling -->
                <line x1="100" y1="15" x2="300" y2="15" stroke="#475569" stroke-width="4" stroke-linecap="round" />
                <circle cx="200" cy="15" r="4" fill="#64748b" />
                
                <!-- Bob position calculations are derived in script -->

                <!-- String -->
                <line x1="200" y1="15" x2={bobX} y2={bobY} stroke="#e2e8f0" stroke-width="1.5" />
                
                <!-- Bob (Mass) -->
                <circle cx={bobX} cy={bobY} r="12" fill="#a855f7" stroke="#d8b4fe" stroke-width="2" />
                
                <!-- Energy bar graphical overlay inside SVG (Right Side) -->
                <g transform="translate(320, 30)">
                  <text x="0" y="-8" fill="#94a3b8" font-size="8" font-family="monospace">ENERGY (J)</text>
                  <!-- Kinetic Energy Bar -->
                  <rect x="0" y="0" width="8" height="60" fill="#1e293b" rx="2" />
                  <rect x="0" y={60 - Math.min(60, kineticEnergy * 1.5)} width="8" height={Math.min(60, kineticEnergy * 1.5)} fill="#10b981" rx="2" />
                  <text x="12" y="32" fill="#10b981" font-size="8" font-family="monospace">KE</text>

                  <!-- Potential Energy Bar -->
                  <rect x="25" y="0" width="8" height="60" fill="#1e293b" rx="2" />
                  <rect x="25" y={60 - Math.min(60, potentialEnergy * 1.5)} width="8" height={Math.min(60, potentialEnergy * 1.5)} fill="#3b82f6" rx="2" />
                  <text x="37" y="32" fill="#3b82f6" font-size="8" font-family="monospace">PE</text>
                </g>
              </svg>
            </div>

            <!-- Parameters control panel -->
            <div class="sliders-grid">
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>String Length ($L$)</span>
                  <span class="value-highlight">{pendulumLength.toFixed(1)} m</span>
                </div>
                <input type="range" min="0.5" max="3.0" step="0.1" bind:value={pendulumLength} class="slider-full" />
              </div>
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Gravity ($g$)</span>
                  <span class="value-highlight">{pendulumGravity.toFixed(2)} m/s²</span>
                </div>
                <div class="material-options">
                  <button class="choice-btn" class:selected={pendulumGravity === 1.62} onclick={() => pendulumGravity = 1.62}>Moon</button>
                  <button class="choice-btn" class:selected={pendulumGravity === 9.81} onclick={() => pendulumGravity = 9.81}>Earth</button>
                  <button class="choice-btn" class:selected={pendulumGravity === 24.79} onclick={() => pendulumGravity = 24.79}>Jupiter</button>
                </div>
              </div>
              <div class="slider-field-row">
                <div class="slider-field" style="flex: 2;">
                  <div class="slider-field-header">
                    <span>Release Angle (&theta;<sub>0</sub>)</span>
                    <span class="value-highlight">{pendulumAngle}°</span>
                  </div>
                  <input type="range" min="5" max="60" step="5" bind:value={pendulumAngle} class="slider-full" />
                </div>
                <div class="action-btn-col">
                  <button class="control-action-btn" onclick={resetPendulum}>Reset</button>
                  <button class="control-action-btn" onclick={() => pendulumActive = !pendulumActive}>
                    {pendulumActive ? 'Pause' : 'Play'}
                  </button>
                </div>
              </div>
            </div>

            <!-- Solver Math Dashboard -->
            <div class="solver-output-box">
              <div class="formula-line">
                <span class="formula-label">Derivations:</span>
                <span class="formula-text">T<sub>0</sub> = 2&pi;&radic;(L/g) | T = T<sub>0</sub>(1 + &theta;<sub>0</sub><sup>2</sup>/16)</span>
              </div>
              <div class="math-breakdown">
                <p>
                  Linear Period (T<sub>0</sub>): {pendulumPeriodT0.toFixed(3)}s<br/>
                  Elliptic Corrected (T): {pendulumPeriodT.toFixed(3)}s (Diff: {((pendulumPeriodT - pendulumPeriodT0)/pendulumPeriodT0 * 100).toFixed(1)}%)
                </p>
                <div class="main-metric">
                  <span class="metric-label">Kinetic + Potential Energy:</span>
                  <span class="metric-val">
                    {(kineticEnergy).toFixed(1)}J + {(potentialEnergy).toFixed(1)}J = {totalEnergy.toFixed(1)}J
                  </span>
                </div>
              </div>
            </div>
          </div>

        {:else if activeSandboxTab === "gas"}
          <!-- IDEAL GAS WIDGET -->
          <div class="sim-container">
            <h4 class="sim-title">Ideal Gas Molecular Kinetic Theory Sandbox</h4>
            
            <div class="svg-wrapper" style="height: 220px; overflow: hidden;">
              <!-- Bouncing Molecules Canvas -->
              <canvas 
                bind:this={canvasEl} 
                width="400" 
                height="210" 
                class="sim-canvas"
              ></canvas>
            </div>

            <!-- Parameter controls -->
            <div class="sliders-grid">
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Temperature ($T$)</span>
                  <span class="value-highlight">{gasTemperature} K</span>
                </div>
                <input type="range" min="100" max="600" step="20" bind:value={gasTemperature} class="slider-full" />
              </div>
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Volume ($V$)</span>
                  <span class="value-highlight">{gasVolume}% size</span>
                </div>
                <input type="range" min="20" max="100" step="5" bind:value={gasVolume} class="slider-full" />
              </div>
              <div class="slider-field">
                <div class="slider-field-header">
                  <span>Molecule Count ($n$)</span>
                  <span class="value-highlight">{gasParticlesCount} particles</span>
                </div>
                <input type="range" min="10" max="80" step="2" bind:value={gasParticlesCount} class="slider-full" />
              </div>
            </div>

            <!-- Solver Math Dashboard -->
            <div class="solver-output-box">
              <div class="formula-line">
                <span class="formula-label">Ideal Gas Equation:</span>
                <span class="formula-text">P = nRT / V</span>
              </div>
              <div class="gas-two-column">
                <div class="gas-stat-item">
                  <span class="g-lbl">Theoretical P:</span>
                  <span class="g-val">{gasPressureTheory.toFixed(1)} kPa</span>
                </div>
                <div class="gas-stat-item">
                  <span class="g-lbl">Wall-Impact P:</span>
                  <span class="g-val">{gasPressureMeasured.toFixed(1)} kPa</span>
                </div>
              </div>
              <div class="speed-formula-block">
                <span>V<sub>rms</sub> = &radic;(3RT/M) &propto; {Math.sqrt(gasTemperature).toFixed(1)} units</span>
              </div>
            </div>
          </div>
        {/if}
      </div>
    </div>
  </div>
</main>

<style>
  /* Standard modern dark-mode stylesheet optimized for webapp development */
  :global(body) {
    margin: 0;
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background-color: #030712;
    color: #cbd5e1;
    overflow-x: hidden;
  }

  .app-viewport {
    display: flex;
    flex-direction: column;
    height: 100vh;
    padding: 1rem 1.5rem;
    box-sizing: border-box;
    gap: 0.75rem;
    background: radial-gradient(circle at 80% 10%, rgba(168, 85, 247, 0.08) 0%, transparent 50%),
                radial-gradient(circle at 10% 90%, rgba(6, 182, 212, 0.05) 0%, transparent 40%);
  }

  /* Header Styling */
  .app-header {
    border-bottom: 1px solid #1e293b;
    padding-bottom: 0.5rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .header-branding {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .logo-area {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .badge-challenge {
    background: linear-gradient(135deg, #a855f7 0%, #06b6d4 100%);
    color: #ffffff;
    font-size: 0.65rem;
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-weight: 800;
    letter-spacing: 0.05em;
    box-shadow: 0 0 10px rgba(168, 85, 247, 0.35);
  }

  .gradient-text {
    font-size: 1.25rem;
    font-weight: 800;
    margin: 0;
    background: linear-gradient(to right, #f8fafc, #d8b4fe, #818cf8);
    -webkit-background-clip: text;
    background-clip: text;
    -webkit-text-fill-color: transparent;
  }

  .system-pills {
    display: flex;
    gap: 0.5rem;
  }

  .pill-green {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    background: rgba(16, 185, 129, 0.1);
    border: 1px solid rgba(16, 185, 129, 0.25);
    padding: 0.25rem 0.6rem;
    border-radius: 9999px;
    font-size: 0.7rem;
    font-weight: 600;
    color: #34d399;
  }

  .pulse-beacon {
    width: 6px;
    height: 6px;
    background-color: #10b981;
    border-radius: 50%;
    box-shadow: 0 0 6px #10b981;
    animation: pulse-ring 2s infinite;
  }

  .pill-info {
    background: rgba(30, 41, 59, 0.6);
    border: 1px solid #334155;
    padding: 0.25rem 0.6rem;
    border-radius: 9999px;
    font-size: 0.7rem;
    font-weight: 500;
    color: #94a3b8;
  }

  .header-desc-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .header-subtitle {
    margin: 0;
    font-size: 0.75rem;
    color: #64748b;
  }

  .local-timestamp {
    font-size: 0.7rem;
    font-family: monospace;
  }

  .time-label {
    color: #475569;
  }

  .time-value {
    color: #64748b;
  }

  /* Dashboard Core Grid Layout */
  .dashboard-grid {
    display: grid;
    grid-template-columns: 1.1fr 0.9fr;
    gap: 1rem;
    flex-grow: 1;
    min-height: 0; /* Important for scroll view inheritance */
  }

  .card {
    background: rgba(15, 23, 42, 0.3);
    border: 1px solid #1e293b;
    border-radius: 12px;
    backdrop-filter: blur(16px);
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  /* LEFT COLUMN: TUTOR PANEL */
  .panel-tutor {
    padding: 0.75rem;
    gap: 0.75rem;
  }

  /* Configuration bar */
  .config-ribbon {
    background: rgba(30, 41, 59, 0.3);
    border: 1px solid #1e293b;
    border-radius: 8px;
    padding: 0.4rem 0.75rem;
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .ribbon-header {
    font-size: 0.7rem;
    font-weight: 700;
    color: #a855f7;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .ribbon-fields {
    display: flex;
    gap: 1rem;
    align-items: center;
    flex-grow: 1;
  }

  .field-item {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    cursor: pointer;
  }

  .field-label {
    font-size: 0.65rem;
    color: #64748b;
    font-weight: 600;
  }

  .select-small {
    background: #0f172a;
    border: 1px solid #334155;
    color: #e2e8f0;
    font-size: 0.65rem;
    padding: 0.15rem 0.4rem;
    border-radius: 4px;
    outline: none;
    cursor: pointer;
  }

  .select-small:focus {
    border-color: #a855f7;
  }

  .slider-mini {
    width: 60px;
    height: 3px;
    accent-color: #a855f7;
    cursor: pointer;
  }

  .slider-val {
    font-size: 0.65rem;
    color: #e2e8f0;
    font-family: monospace;
  }

  /* Lab shortcuts section */
  .shortcuts-container {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  .section-title-bar {
    display: flex;
    align-items: center;
    gap: 0.4rem;
  }

  .section-title-bar h3 {
    margin: 0;
    font-size: 0.75rem;
    font-weight: 700;
    color: #94a3b8;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .shortcuts-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 0.5rem;
  }

  .shortcut-card {
    background: rgba(30, 41, 59, 0.25);
    border: 1px solid #1e293b;
    border-radius: 8px;
    padding: 0.5rem 0.75rem;
    cursor: pointer;
    text-align: left;
    display: flex;
    align-items: center;
    justify-content: space-between;
    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
  }

  .shortcut-card:hover:not(:disabled) {
    border-color: #06b6d4;
    background: rgba(6, 182, 212, 0.05);
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(6, 182, 212, 0.1);
  }

  .shortcut-card.active {
    border-color: #a855f7;
    background: rgba(168, 85, 247, 0.08);
    box-shadow: 0 4px 12px rgba(168, 85, 247, 0.15);
  }

  .shortcut-meta {
    display: flex;
    flex-direction: column;
    gap: 0.15rem;
  }

  .shortcut-name {
    font-size: 0.75rem;
    font-weight: 700;
    color: #f1f5f9;
  }

  .shortcut-desc {
    font-size: 0.6rem;
    color: #64748b;
  }

  .shortcut-arrow {
    font-size: 0.85rem;
    color: #475569;
    transition: transform 0.2s;
  }

  .shortcut-card:hover .shortcut-arrow {
    color: #06b6d4;
    transform: translateX(2px);
  }

  /* Console Output Wrapper */
  .console-wrapper {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }

  .console-header-bar {
    background: #090d16;
    border: 1px solid #1e293b;
    border-bottom: none;
    border-radius: 8px 8px 0 0;
    padding: 0.4rem 0.75rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .console-title {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    font-family: monospace;
    font-size: 0.7rem;
    color: #64748b;
  }

  .cmd-prompt {
    color: #06b6d4;
    font-weight: bold;
  }

  .console-metrics {
    font-family: monospace;
    font-size: 0.65rem;
  }

  .indicator-computing {
    color: #d8b4fe;
    animation: pulse-slow 1.5s infinite;
  }

  .indicator-idle {
    color: #10b981;
  }

  .terminal-screen {
    background: #020617;
    border: 1px solid #1e293b;
    border-left: 3px solid #a855f7;
    border-radius: 0 0 8px 8px;
    padding: 0.85rem;
    flex-grow: 1;
    overflow-y: auto;
    font-family: 'JetBrains Mono', 'Fira Code', monospace;
    font-size: 0.8rem;
    line-height: 1.5;
    color: #38bdf8;
    box-shadow: inset 0 4px 20px rgba(0, 0, 0, 0.7);
  }

  .terminal-feed {
    word-break: break-word;
  }

  :global(.terminal-user-query) {
    background: rgba(168, 85, 247, 0.08);
    border-left: 2px solid #a855f7;
    padding: 0.35rem 0.6rem;
    margin: 0.5rem 0 0.8rem 0;
    border-radius: 2px;
  }

  :global(.query-text) {
    color: #f1f5f9;
    font-weight: 500;
  }

  :global(.terminal-assistant-response) {
    margin-bottom: 1rem;
    border-bottom: 1px dashed rgba(30, 41, 59, 0.6);
    padding-bottom: 0.8rem;
  }

  :global(.terminal-assistant-response:last-child) {
    border-bottom: none;
    padding-bottom: 0;
  }

  .btn-clear-console {
    background: rgba(30, 41, 59, 0.5);
    border: 1px solid #334155;
    color: #94a3b8;
    padding: 0.15rem 0.5rem;
    border-radius: 4px;
    font-size: 0.65rem;
    cursor: pointer;
    font-family: inherit;
    transition: all 0.2s ease;
    margin-right: 0.5rem;
  }

  .btn-clear-console:hover:not(:disabled) {
    background: rgba(239, 68, 68, 0.15);
    border-color: #ef4444;
    color: #f87171;
  }

  /* Blinking cursor effect */
  .blinking-cursor {
    color: #a855f7;
    font-weight: 900;
    animation: blink-anim 1s step-end infinite;
  }

  /* Markdown formatted styles inside console */
  :global(.term-h1) {
    color: #f8fafc;
    font-size: 1.05rem;
    margin: 0.75rem 0 0.35rem 0;
    border-bottom: 1px solid rgba(255, 255, 255, 0.08);
    padding-bottom: 0.15rem;
  }

  :global(.term-h2) {
    color: #e2e8f0;
    font-size: 0.95rem;
    margin: 0.6rem 0 0.3rem 0;
  }

  :global(.term-h3) {
    color: #cbd5e1;
    font-size: 0.85rem;
    margin: 0.5rem 0 0.25rem 0;
    text-transform: uppercase;
    letter-spacing: 0.02em;
  }

  :global(.term-bold) {
    color: #f1f5f9;
    font-weight: 700;
  }

  :global(.term-italic) {
    color: #93c5fd;
    font-style: italic;
  }

  :global(.term-code) {
    background: rgba(30, 41, 59, 0.6);
    color: #fda4af;
    padding: 0.1rem 0.25rem;
    border-radius: 3px;
    font-size: 0.75rem;
  }

  :global(.term-code-block) {
    background: #0f172a;
    border: 1px solid #1e293b;
    border-radius: 6px;
    padding: 0.5rem;
    margin: 0.5rem 0;
    overflow-x: auto;
  }

  :global(.code-lang) {
    font-size: 0.55rem;
    color: #64748b;
    text-transform: uppercase;
    border-bottom: 1px solid #1e293b;
    padding-bottom: 0.2rem;
    margin-bottom: 0.35rem;
  }

  :global(.system-msg) {
    color: #a855f7;
    font-weight: 600;
  }

  :global(.error-msg) {
    color: #ef4444;
    font-weight: bold;
  }

  /* Collapsible Thought Process */
  :global(.term-think-details) {
    background: rgba(15, 23, 42, 0.6);
    border: 1px dashed #334155;
    border-radius: 6px;
    padding: 0.6rem 0.8rem;
    margin-bottom: 0.85rem;
  }

  :global(.term-think-summary) {
    font-size: 0.75rem;
    color: #94a3b8;
    cursor: pointer;
    font-weight: 600;
    user-select: none;
    outline: none;
  }

  :global(.term-think-summary:hover) {
    color: #cbd5e1;
  }

  :global(.term-think-body) {
    font-size: 0.75rem;
    color: #64748b;
    font-style: italic;
    margin-top: 0.4rem;
    border-left: 2px solid #334155;
    padding-left: 0.65rem;
    line-height: 1.45;
  }

  /* List items */
  :global(.term-li) {
    display: list-item;
    list-style-type: disc;
    margin-left: 1.35rem;
    margin-bottom: 0.3rem;
    color: #cbd5e1;
  }

  :global(.math-error) {
    color: #f43f5e;
    background: rgba(244, 63, 94, 0.1);
    padding: 0.1rem 0.25rem;
    border-radius: 3px;
    font-family: monospace;
  }


  /* Prompt Input Area */
  .input-tray {
    display: flex;
    gap: 0.5rem;
  }

  .student-text-input {
    flex-grow: 1;
    background: #090d16;
    border: 1px solid #1e293b;
    color: #f8fafc;
    padding: 0.65rem 0.85rem;
    border-radius: 8px;
    font-size: 0.75rem;
    outline: none;
    transition: all 0.2s;
  }

  .student-text-input:focus {
    border-color: #06b6d4;
    box-shadow: 0 0 8px rgba(6, 182, 212, 0.15);
  }

  .btn-execute {
    background: linear-gradient(135deg, #a855f7 0%, #6366f1 100%);
    color: #ffffff;
    border: none;
    padding: 0 1.25rem;
    border-radius: 8px;
    font-weight: 700;
    font-size: 0.75rem;
    cursor: pointer;
    transition: all 0.2s;
    box-shadow: 0 4px 10px rgba(168, 85, 247, 0.2);
  }

  .btn-execute:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 14px rgba(168, 85, 247, 0.35);
  }

  .btn-execute:disabled {
    background: #1e293b;
    color: #475569;
    cursor: not-allowed;
    box-shadow: none;
    transform: none;
  }

  /* RIGHT COLUMN: SIMULATOR SANDBOX */
  .panel-sandbox {
    padding: 0.75rem;
    gap: 0.75rem;
  }

  /* Navigation tab header */
  .sandbox-tabs {
    display: flex;
    background: rgba(30, 41, 59, 0.3);
    border: 1px solid #1e293b;
    padding: 0.25rem;
    border-radius: 8px;
    gap: 0.25rem;
  }

  .tab-btn {
    flex: 1;
    background: transparent;
    border: none;
    color: #64748b;
    padding: 0.45rem;
    font-size: 0.7rem;
    font-weight: 700;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .tab-btn:hover {
    color: #e2e8f0;
  }

  .tab-btn.active {
    background: #0f172a;
    color: #a855f7;
    border: 1px solid #1e293b;
    box-shadow: 0 2px 6px rgba(0,0,0,0.4);
  }

  /* Simulation Content area */
  .sandbox-viewport {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }

  .sim-container {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    height: 100%;
  }

  .sim-title {
    margin: 0;
    font-size: 0.8rem;
    font-weight: 700;
    color: #f1f5f9;
    letter-spacing: 0.02em;
    border-left: 2px solid #06b6d4;
    padding-left: 0.5rem;
  }

  .svg-wrapper {
    background: #020617;
    border: 1px solid #1e293b;
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: inset 0 2px 10px rgba(0,0,0,0.6);
  }

  .sim-svg {
    width: 100%;
    max-height: 200px;
  }

  .sim-canvas {
    width: 100%;
    height: 100%;
    background: transparent;
    display: block;
  }

  /* Sliders grid configuration */
  .sliders-grid {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    background: rgba(30, 41, 59, 0.15);
    border: 1px solid #1e293b;
    padding: 0.6rem;
    border-radius: 8px;
  }

  .slider-field-row {
    display: flex;
    gap: 0.75rem;
    align-items: flex-end;
  }

  .slider-field {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .slider-field-header {
    display: flex;
    justify-content: space-between;
    font-size: 0.65rem;
    font-weight: 600;
    color: #94a3b8;
  }

  .value-highlight {
    color: #06b6d4;
    font-family: monospace;
  }

  .slider-full {
    width: 100%;
    height: 4px;
    accent-color: #06b6d4;
    cursor: pointer;
  }

  /* Permeability Material switcher */
  .material-options {
    display: flex;
    gap: 0.35rem;
  }

  .choice-btn {
    flex: 1;
    background: #0f172a;
    border: 1px solid #334155;
    color: #94a3b8;
    font-size: 0.6rem;
    font-weight: 700;
    padding: 0.25rem;
    border-radius: 4px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .choice-btn:hover {
    color: #f1f5f9;
    border-color: #475569;
  }

  .choice-btn.selected {
    border-color: #06b6d4;
    background: rgba(6, 182, 212, 0.1);
    color: #06b6d4;
  }

  .action-btn-col {
    display: flex;
    gap: 0.35rem;
  }

  .control-action-btn {
    background: #1e293b;
    border: 1px solid #334155;
    color: #e2e8f0;
    font-size: 0.65rem;
    font-weight: bold;
    padding: 0.3rem 0.6rem;
    border-radius: 4px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .control-action-btn:hover {
    background: #334155;
    border-color: #475569;
  }

  /* Mathematical calculation output dashboard */
  .solver-output-box {
    background: rgba(9, 13, 22, 0.6);
    border: 1px solid rgba(6, 182, 212, 0.15);
    border-left: 3px solid #06b6d4;
    border-radius: 6px;
    padding: 0.5rem 0.75rem;
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  .formula-line {
    display: flex;
    justify-content: space-between;
    font-size: 0.65rem;
  }

  .formula-label {
    color: #475569;
    font-weight: bold;
  }

  .formula-text {
    font-family: 'JetBrains Mono', monospace;
    color: #94a3b8;
  }

  .math-breakdown {
    font-size: 0.65rem;
    font-family: 'JetBrains Mono', monospace;
    color: #64748b;
    line-height: 1.4;
  }

  .main-metric {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid rgba(255, 255, 255, 0.05);
    padding-top: 0.35rem;
    margin-top: 0.25rem;
  }

  .metric-label {
    font-size: 0.7rem;
    font-weight: 700;
    color: #e2e8f0;
  }

  .metric-val {
    font-size: 0.85rem;
    font-weight: 800;
    color: #06b6d4;
    font-family: monospace;
    text-shadow: 0 0 6px rgba(6, 182, 212, 0.3);
  }

  /* Ideal Gas Law Solver layout */
  .gas-two-column {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 0.75rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.05);
    padding-bottom: 0.25rem;
  }

  .gas-stat-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .g-lbl {
    font-size: 0.65rem;
    color: #94a3b8;
  }

  .g-val {
    font-size: 0.75rem;
    font-weight: bold;
    font-family: monospace;
    color: #06b6d4;
  }

  .speed-formula-block {
    font-size: 0.6rem;
    color: #475569;
    font-family: monospace;
    text-align: right;
  }

  /* SVG & CSS Keyframe Animations */
  @keyframes pulse-ring {
    0%, 100% { transform: scale(1); opacity: 1; }
    50% { transform: scale(1.3); opacity: 0.5; }
  }

  @keyframes pulse-slow {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.65; }
  }

  @keyframes blink-anim {
    from, to { color: transparent }
    50% { color: #a855f7 }
  }

  @keyframes dash {
    to {
      stroke-dashoffset: -20;
    }
  }

  /* Responsive screen configurations */
  @media (max-width: 900px) {
    .dashboard-grid {
      grid-template-columns: 1fr;
      overflow-y: auto;
    }

    .app-viewport {
      height: auto;
      overflow-y: auto;
    }

    .terminal-screen {
      height: 250px;
    }
  }
</style>
